### ISSUE TITLE
Convergence

### ISSUE THREAD

**Issue by tsupplis** [agn453/HI-TECH-Z80-C#2]
I did exactly the same work ~ 2 years ago but did not feel bold to share. Missing some of your patches. I am realigning and will publish on git. Any interest is joining effort?
In particular the overlays...

**Comment by tsupplis** [comment]
In part

**Comment by tsupplis** [comment]
FYI added my version to git. https://github.com/tsupplis/zxcc-htc
It contains most of the changes of John Elliot + personal clean up + overlay + beginning of
alignment with you.

**Comment by tsupplis** [comment]
I did a good bit of alignment already. key remaining differences
- overlays (and consequently the c.com driver)
- stricmp (will align on you)
- the exit (not sure. need to look at the weird pops in my version)
- built using zxcc

**Comment by agn453** [comment]
I'm happy to collaborate and align versions of HI-TECH C for the Z80.

Currently I use the compiler natively on Z80 and Z280 systems as well as via ZXCC on macOS and Linux (Raspberry Pi Raspbian).

It would be good if our updates could be merged (as much as possible), and kept in a consolidated place - since too much scattering of information makes it harder for people to find.  I'm happy to consider pull requests too.

I started gathering MSX/MSX2 stuff too since others in the Retro-computing hobby are interested in these too - but time constraints slowed my progress (and I don't have a MSX machine to test things on).

I'm familiar with the overlay capabilities that were used by Ron Murray in his implementation of ZMODEM (ZMP15, RZMP16 and HTC-OVL) but not yet looked at adding it.  Is this what you're referring to?

Tony

**Comment by tsupplis** [comment]
for HTC-OVL, absolutely correct. It required quite a lot of work on the C driver. 
I am doing code clean up to be as aligned as I can on you as a start. It will take a little while. I am keeping up to date. Then I will drop my project and rebase/fork from you ... This will give us a way to communicate by PR 😉
