### ISSUE TITLE
It doesn't run on the Agon Light yet and it's not 24 bit to suit the eZ80 CPUs

### ISSUE THREAD

**Issue by snakebyte69** [agn453/HI-TECH-Z80-C#38]
https://www.thebyteattic.com/p/agon.html

**Comment by agn453** [comment]
This repo currently targets a Z80 computer running CP/M 2.2 or later (CP/M Plus or compatible is preferred) using a standard transient programming area (TPA) in 64Kb of memory (i.e. with the resident BDOS).

I have done some work to incorporate the additional instructions used by the Z180 and Z280 processors in the C libraries (but not in the compiler executables).

I expect there could be some enhancements possible for the eZ80 - but for this to be really useful, the operating system would need to support 24-bit addressing modes too - otherwise you'd still be limited to what is in effect a traditional 64Kb memory footprint CP/M machine.

Tony
